### ISSUE TITLE
New version(s)

### ISSUE THREAD

**Issue by alanz** [Infinisil/all-hies#57]
FYI we now have https://github.com/haskell/haskell-ide-engine/releases/tag/1.4

But to add complexity, we now also have https://github.com/haskell/haskell-language-server/releases/tag/0.1, which should have basically the same packaging process as hie.

I am not sure if that belongs here, or should be somewhere else?

**Comment by Anton-Latukha** [comment]
:flippin the table:

... actually:
```
(┛ಠ_ಠ)┛彡┻━┻
```

Well, lets see:
`stack2nix` does not work, `nixpkgs` does not work, `all-hies` does not work, you informing that `Haskell IDE Engine` soon would not work also, `GHC 8.10 new garbage collector` falls. My oldie `Emacs` is also thinking of...

What we can do with it? We can form a set from it! And lets build a category.

As it is said: "Good NixOS/Haskell/HIE set up you got there..."

So what we have here:... a very stable process development.

I've lost a couple of jobs as a DevOps because of such stable situations happening. Stuff was not assembling, so - that means I could not build stuff - so I am not a DevOps now. I lost my Ops, and so I am a Dev, can just use a Notepad, and indeed, a paper one.

Because the end product is the text, even if it is in isomorphic type writing.

---


But honestly:
```
(\^.^)\︵┳━┳
```
Thank you, and we see your goodness. And that the toolchain would be great. We all in this together.
And thank you for informing.

If it would come out a little a lot like `Emacs` - we would bless you.

**Comment by infinisil** [comment]
With #64 merged HIE was updated to a recent unstable version (after 1.4)
