### ISSUE TITLE
Building other OSX fails

### ISSUE THREAD

**Issue by dawehner** [Infinisil/all-hies#7]
I've tried to follow the build instructions under osx:

```
let
  all-hies = import (fetchTarball "https://github.com/infinisil/all-hies/tarball/master") {};
in
{
  # ...
}
```

without cacheix being configured.

This results into the error described in https://github.com/NixOS/nixpkgs/issues/6390
Beside having math.h inside `/usr/include` and setting the environment variables it still fails.

@mpickering in the fp slack suggested to use cacheix which resolved the issue for me. On top of that though he suggested to create an issue here, given that @Infinisil is really helpful.

Let me know when you want any further system information

**Comment by infinisil** [comment]
Thanks for pointing this out, but I won't be trying to make this compile on different macOS versions.

I initiallly tried to build it with Mojave, which after trying for a day I gave up on because older nixpkgs versions (which are needed to get older GHC versions) don't work at all because of [#42719](https://github.com/NixOS/nixpkgs/issues/42719) (and a series of other problems).

Fortunately I still had a High Sierra installer, which Apple doesn't even allow downloading anymore, with which I was able to build all versions with some patching (see https://github.com/Infinisil/all-hies/pull/4). And with cachix I can provide caches for these builds, which will even work on other macOS versions.

What macOS version are you using? Yosemite? I can adjust the readme to indicate which macOS versions can build all versions (to our best knowledge).

**Comment by dawehner** [comment]
Thank you for your incredible quickly reply

I'm using Mojave (10.14.4) at this point in time.

**Comment by infinisil** [comment]
Ah, weird, I didn't encounter that specific issue with my Mojave. But that's just another reason for me not to want to worry about different macOS versions :)

**Comment by infinisil** [comment]
Alright I added [a readme section](https://github.com/infinisil/all-hies#building-without-cached-builds) on that in 777b6665c1671feaa3c3eb74d10dd6f79ec1302c

**Comment by chuwy** [comment]
FYI, I managed to compile all-hies on Mojave with

```
$ nix-env -iA unstableFallback.selection --arg selector 'p: { inherit (p) ghc865; }' -f https://github.com/infinisil/all-hies/tarball/master
```

But in the end running into following cabal-helper error when LanguageClient Server starts:

```
readCreateProcess: /nix/store/dkg051wnbqvg8paack4f7lvivha5hpr4-cabal-helper-0.9.0.0/bin/cabal-helper-wrapper \"--with-ghc=ghc\" \"--with-ghc-pkg=ghc-pkg\" \"--with-cabal=cabal\" \"v1-style\" \"/Users/chuwy/workspace/opus\" \"/Users/chuwy/workspace/opus/dist-newstyle/build/x86_64-osx/ghc-8.6.5/opus-0.1.0.0\" \"package-db-stack\" \"flags\" \"compiler-version\" \"ghc-merged-pkg-options\" \"config-flags\" \"non-default-config-flags\" \"ghc-src-options\" \"ghc-pkg-options\" \"ghc-lang-options\" \"ghc-options\" \"source-dirs\" \"entrypoints\" \"needs-build-output\" (exit 1): failed
```

Not sure though if this is something new.

**Comment by infinisil** [comment]
Yeah, HIE for GHC 8.6.5 compiles just fine on Mojave, and so do most others, only a couple don't.

You're probably encountering the last point here: https://github.com/haskell/haskell-ide-engine#nix-cabal-helper-no-such-file-or-directory (which I just PR'd recently)

**Comment by chuwy** [comment]
Thanks Silvan, that (or something else maybe) worked, but I ended up with HIE working only with `base`. Any extra dependency crashes it with:

```
Could not load module ‘Data.Aeson’
It is a member of the hidden package ‘aeson-1.4.3.0’.
...and others
```

I remember similar situation on another machine and hie-nix. Back then `cabal new-build` helped, but not this time.

Edit: in fact it was  `cabal new-build`  that fixed cabal-helper error because it was complaining on:

```
cabal-helper-wrapper: /Users/chuwy/workspace/opus/dist-newstyle/build/x86_64-osx/ghc-8.6.5/opus-0.1.0.0/setup-config: openFile: does not exist (No such file or directory)
```

**Comment by infinisil** [comment]
@chuwy Can you open a new issue with your problem that includes a reproducible example?

**Comment by chuwy** [comment]
Thanks, @Infinisil. I think I finally made it work by switching to `cabal build` from `new-build` and cleaning everything up. Does it still deserve a ticket or is it some kind of expected behavior? (Sorry if the question is dumb, I'm fairly new to cabal and nix)

**Comment by infinisil** [comment]
Ah yeah, cabal new-build support is still experimental in HIE as far as I know. An issue in the HIE repo might be more fitting for that if you want to report it (unless somebody else already did).
